Added better messages for soup
clicepfl/roboclic-archived pull request #10
Opened 2022-06-07 18:23 UTC by huguesdevimeux

## Before : 
![image](https://user-images.githubusercontent.com/36239975/172455077-2cd82652-7edf-4084-9454-d18a1d840e5b.png)
 ## After:
![image](https://user-images.githubusercontent.com/36239975/172455115-5d41c366-32aa-4a45-833f-809ec220040c.png)

Closes #9

2022-06-07 18:54 UTC, s314cy requested changes

2022-06-07 18:54 UTC, s314cy commented on robot/handlers/soup.py
> +    return TEMPLATE_TEXT.format(header=header, text_dishes="\n".join([str(p) for p in list_dishes]))
générateur plutôt qu'une liste? :) du genre:

`"\n".join(str(p) for p in list_dishes)`

2022-06-07 18:54 UTC, s314cy commented on robot/handlers/soup.py
> +    # Removes non-Lausanne resultsMARKDOWN_V2
?

2022-06-07 18:54 UTC, s314cy commented on robot/handlers/soup.py
> +from dataclasses import dataclass
faudrait grouper les imports de la librairie standard avec ceux déjà présents (ici `import os`)

2022-06-07 18:54 UTC, s314cy commented on robot/handlers/soup.py
> +@dataclass
coooool je connaissais pas

2022-06-07 19:00 UTC, s314cy commented
par rapport à ton dernier commit 7512210d1227c773c2e18010e48ad09476e5f7bf, tu peux

```git reset HEAD^
git commit -a --amend --no-edit
git push -f```

2022-06-07 19:32 UTC, huguesdevimeux commented
> par rapport à ton dernier commit 7512210d1227c773c2e18010e48ad09476e5f7bf, tu peux
> 
> 
> 
> ```
> 
> git reset HEAD^
> 
> git commit -a --amend --no-edit
> 
> git push -f
> 
> ```

Vous stashez pas les PRs ici ?

2022-06-07 20:34 UTC, huguesdevimeux commented on robot/handlers/soup.py
> +    return TEMPLATE_TEXT.format(header=header, text_dishes="\n".join([str(p) for p in list_dishes]))
Ah ouais, pas bête merci beaucoup !

2022-06-07 20:34 UTC, huguesdevimeux commented on robot/handlers/soup.py
> +    # Removes non-Lausanne resultsMARKDOWN_V2
ooops 
```suggestion
    # Removes non-Lausanne results
```

2022-06-07 20:34 UTC, huguesdevimeux commented on robot/handlers/soup.py
> +from dataclasses import dataclass
ça marche !

2022-06-08 08:57 UTC, s314cy requested changes
oublie pas de lint ton code avec `black` (`pip install black`)

2022-06-08 08:57 UTC, s314cy commented on robot/handlers/soup.py
> +from dataclasses import dataclass
les imports les plus spécifiques en premier :^)

2022-06-08 08:57 UTC, s314cy commented on robot/handlers/soup.py
>  from bs4 import BeautifulSoup as bs
les imports les plus spécifiques en premier :^)

2022-06-08 08:57 UTC, s314cy commented on robot/handlers/soup.py
> +from ..config import MENU, REQUEST_TIMER, SOUP
les imports des modules locaux en premier

2022-06-08 12:04 UTC, huguesdevimeux commented on robot/handlers/soup.py
> +from ..config import MENU, REQUEST_TIMER, SOUP
Je vais faire ça, mais si je puis me permettre une humble suggestion, ça serait mieux de requérir l'inverse, puisque c'est ce que comme ça que fait`isort` (le trieurs d'importations que j'ai utilisé), et c'est aussi la convention générale la plus utilisée à ma connaissance

2022-06-08 12:05 UTC, huguesdevimeux commented on robot/handlers/soup.py
> +from ..config import MENU, REQUEST_TIMER, SOUP
Pour référence, https://stackoverflow.com/questions/20762662/whats-the-correct-way-to-sort-python-import-x-and-from-x-import-y-statement

2022-06-08 17:23 UTC, s314cy approved these changes

2022-06-08 17:23 UTC, merged