Niklespam
clicepfl/roboclic-archived pull request #25
Opened 2022-09-10 12:31 UTC by LucasTrg

g codé avec mon tel, reviewez avec votre cerveau, pas avec votre coeur, :crossed_swords:

2022-09-16 13:35 UTC, LucasTrg commented
petit ping @DeepGreen1 @s314cy

2022-09-26 08:56 UTC, LucasTrg commented
@DeepGreen1 @s314cy

2022-09-26 08:58 UTC, s314cy commented on robot/handlers/bureau.py
> +	"Je suis à Satellite",
excellente initiative

2022-09-26 09:00 UTC, s314cy requested changes, later dismissed
pas testé mais le code a l'air bon 👍 

go tester en prod nan?

2022-09-26 09:00 UTC, s314cy commented on robot/handlers/bureau.py
> +	"Je suis à Satellite",
excellente initiative

2022-09-26 09:00 UTC, s314cy commented on robot/handlers/soup.py
> +        return f"🍽️{'🥬' if self.vegetarian else '🍖'}<b> {min(self.prices)} CHF</b> - <i>{self.name_resto}</i> → {self.dish_name}."
non à l'élevage intenstif 💪

2022-09-26 09:00 UTC, s314cy commented on robot/handlers/soup.py
> +        alias = {"La Tabl": "Vallotton", "Maharaj": "Maharaja", "Satelli":"Sat"}
magnifique

2022-09-26 09:00 UTC, s314cy commented on robot/handlers/soup.py
> +       REQUEST_TIMER["soup_group"]=[]
c'est pas linté

2022-09-26 09:00 UTC, s314cy commented on robot/handlers/soup.py
> +    if update.message.chat_id in REQUEST_TIMER["soup_group"] and (now-REQUEST_TIMER["soup_group"][update.message.chat_id][0]).total_seconds() < 3600:
c pa linté

2022-09-26 13:31 UTC, LucasTrg commented on robot/handlers/soup.py
> +    if update.message.chat_id in REQUEST_TIMER["soup_group"] and (now-REQUEST_TIMER["soup_group"][update.message.chat_id][0]).total_seconds() < 3600:
Ce serait linté si on avait des pre-commit

2022-09-26 13:31 UTC, LucasTrg commented on robot/handlers/soup.py
> +    if update.message.chat_id in REQUEST_TIMER["soup_group"] and (now-REQUEST_TIMER["soup_group"][update.message.chat_id][0]).total_seconds() < 3600:
je fait ça dans la prochaine PR quand on commence à travailler sur les githubs actions

2022-10-09 09:22 UTC, LucasTrg commented on robot/handlers/soup.py
> +        alias = {"La Tabl": "Vallotton", "Maharaj": "Maharaja", "Satelli":"Sat"}
```suggestion
        alias = {"La Tabl": "Vallotton", "Maharaj": "Maharaja", "Satelli": "Sat"}
```

2022-10-09 09:23 UTC, LucasTrg commented on robot/handlers/soup.py
> +                text="🙄",
```suggestion
                text = "🙄",
```

2022-10-09 09:23 UTC, LucasTrg commented on robot/handlers/soup.py
> +       REQUEST_TIMER["soup_group"]=[]
```suggestion
       REQUEST_TIMER["soup_group"] = []
```

2022-10-09 09:23 UTC, LucasTrg commented on robot/handlers/soup.py
> +    REQUEST_TIMER["soup_group"][update.message.chat_id]=(now, soup_id)
```suggestion
    REQUEST_TIMER["soup_group"][update.message.chat_id] = (now, soup_id)
```

2022-10-09 09:23 UTC, LucasTrg commented on robot/handlers/soup.py
> +                chat_id=update.message.chat_id,
```suggestion
                chat_id = update.message.chat_id,
```

2022-10-09 09:24 UTC, LucasTrg commented on robot/handlers/soup.py
> +                reply_to_message_id=REQUEST_TIMER["soup_group"][update.message.chat_id][1],
```suggestion
                reply_to_message_id = REQUEST_TIMER["soup_group"][update.message.chat_id][1],
```

2022-10-09 09:24 UTC, LucasTrg commented on robot/handlers/soup.py
> +                disable_notification=True)
```suggestion
                disable_notification = True)
```

2022-10-09 09:25 UTC, merged