42 dockerisation
clicepfl/roboclic-archived pull request #43
Opened 2023-09-04 10:21 UTC by Thechi2000

Closes #42

I tested the image, everything is fine.
The docker actions is the one provided by Github, I just removed the cron-scheduled runs.

2023-09-05 09:43 UTC, dialexo requested changes

2023-09-05 09:43 UTC, dialexo commented on Dockerfile
> +
Is there an equivalent to the `node` user in the `node` image? I.e. ensure that we do not run (and ideally not build either) as root.

2023-09-05 16:52 UTC, NoeTerrier commented on Dockerfile
> +
Are you thinking of something like:

```dockerfile
RUN useradd -u 1234 my-user
USER my-user
```
?

2023-09-06 12:32 UTC, dialexo approved these changes

2023-09-06 12:34 UTC, merged